# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 250)
        MainWindow.setStyleSheet("background-color: rgb(77, 76, 120);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(37, 44, 57);")
        self.centralwidget.setObjectName("centralwidget")
        self.input_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name.setGeometry(QtCore.QRect(20, 96, 331, 31))
        font = QtGui.QFont()
        font.setFamily("HelveticaNeueCyr")
        font.setPointSize(10)
        font.setBold(False)
        self.input_name.setFont(font)
        self.input_name.setStyleSheet("border: 2px solid #c8c2e9;\n"
"border-radius: 8;\n"
"color: rgb(138, 135, 178);")
        self.input_name.setMaxLength(40)
        self.input_name.setObjectName("input_name")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(28, 83, 142, 19))
        font = QtGui.QFont()
        font.setFamily("HelveticaNeueCyr")
        font.setPointSize(10)
        font.setBold(False)
        self.labelName.setFont(font)
        self.labelName.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelName.setObjectName("labelName")
        self.button_addLink = QtWidgets.QPushButton(self.centralwidget)
        self.button_addLink.setGeometry(QtCore.QRect(130, 170, 130, 40))
        font = QtGui.QFont()
        font.setFamily("HelveticaNeueCyr")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.button_addLink.setFont(font)
        self.button_addLink.setStyleSheet("QPushButton{\n"
"border-color: rgb(200, 194, 233);\n"
"color:rgb(255,255,255);\n"
"border-radius: 20;\n"
"border: 2px solid #C8C2E9;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(200, 194, 233);\n"
"}")
        self.button_addLink.setObjectName("button_addLink")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(28, 23, 58, 19))
        font = QtGui.QFont()
        font.setFamily("HelveticaNeueCyr")
        font.setPointSize(10)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.input_link = QtWidgets.QLineEdit(self.centralwidget)
        self.input_link.setGeometry(QtCore.QRect(20, 36, 331, 31))
        font = QtGui.QFont()
        font.setFamily("HelveticaNeueCyr")
        font.setPointSize(10)
        font.setBold(False)
        self.input_link.setFont(font)
        self.input_link.setStyleSheet("border: 2px solid #c8c2e9;\n"
"border-radius: 8;\n"
"color: rgb(138, 135, 178);")
        self.input_link.setMaxLength(40)
        self.input_link.setObjectName("input_link")
        self.input_name.raise_()
        self.button_addLink.raise_()
        self.input_link.raise_()
        self.label.raise_()
        self.labelName.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelName.setText(_translate("MainWindow", "Имя пользователя"))
        self.button_addLink.setText(_translate("MainWindow", "ДОБАВИТЬ"))
        self.label.setText(_translate("MainWindow", "Ссылка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
